connected "add figure page” to backend and showed indication when item is added successfully
Claymore-Organization/Claymore pull request #39
Opened 2022-04-23 20:21 UTC by SeanEZhou

2022-04-24 18:21 UTC, bluo999 requested changes
Just a small thing, otherwise looks good.

2022-04-24 18:21 UTC, bluo999 commented on frontend/src/components/NewFigureForm.tsx
> +      const sendData = axios.post('https://us-central1-claymore-d6749.cloudfunctions.net/default/figure', data);
Config again

2022-04-26 21:37 UTC, SeanEZhou commented
@bluo999 Moved path to config as advised

2022-04-27 21:09 UTC, bluo999 approved these changes

2022-04-28 00:21 UTC, merged